---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

jobs:
  workflows:
    uses: lazytarget-homeassistant-apps/workflows/.github/workflows/labels.yaml@65bd42230a18643538648b58fbdcbf386a870bb4
