---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  workflows:
    uses: lazytarget-homeassistant-apps/workflows/.github/workflows/pr-labels.yaml@a49df5784a10fbff95c14918244b619a47a7b6da
