---
name: PR Labels

# yamllint disable-line rule:truthy
on:
  pull_request_target:
    types:
      - opened
      - labeled
      - unlabeled
      - synchronize

jobs:
  workflows:
    uses: lazytarget-homeassistant-apps/workflows/.github/workflows/pr-labels.yaml@65bd42230a18643538648b58fbdcbf386a870bb4
